In [ ]:
print('hi')

hi


In [ ]:
import numpy as np

In [ ]:
#b.Создайте массив из 10 нулей
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#c.Создать массив из 10 единиц
array=np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#d.Создать массив из 10 пятерок
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#e.Создать массив из целых чисел от 10 до 50
array=np.arange(10,51)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#f.Создать массив из четных чисел от 10 до 50
array=np.arange(10,51,2)
print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#g.Создать матрицу 3х3 с числами от 0 до 8
array=np.arange(0,9)
array=array.reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#h.Создать единичную матрицу 3x3
array=np.ones((3,3))
print(array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#i.Используйте NumPy для генерации случайного числа от 0 до 1
array=np.random.rand()
print(array)

0.2319165055800727


In [ ]:
#j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
array=np.random.rand(25)
print(array)

[0.10812121 0.67509274 0.71222448 0.63346119 0.56158108 0.52339511
 0.13606461 0.70297928 0.39931264 0.64078426 0.91919688 0.59971911
 0.19239936 0.29547154 0.71351683 0.04336579 0.66625493 0.75709545
 0.22176998 0.62809143 0.42432855 0.91335257 0.04244391 0.962863
 0.34738444]


In [ ]:
#k.Создайте матрицу, используя функции библиотеки NumPy:
array=np.arange(0.01,1.01,0.01).reshape(10,10)
print(array)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
#это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#l.
print(mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
#m.Написать код обращения к элементу, который вернет значение  20 из стартовой матрицы задачи l.
print(mat[3][4])

20


In [ ]:
from numpy.core.arrayprint import array2string
#n.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
#array([[ 2],
#       [ 7],
#       [12]])
print(mat[0:3,1].reshape(3,1))

[[ 2]
 [ 7]
 [12]]


In [ ]:
#o.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
#array([21, 22, 23, 24, 25])
print(mat[3:][1:])

[[21 22 23 24 25]]


In [ ]:
#p.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
#array([[16, 17, 18, 19, 20],
#       [21, 22, 23, 24, 25]])
print(mat[2:][1:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#q.Получить сумму всех значений в стартовой матрице mat
print(mat.sum())

325


In [ ]:
#r.Получить стандартное отклонение в стартовой матрице mat
print(mat.std())

7.211102550927978


In [ ]:
#s.Получить сумму значений в колонках в стартовой матрице mat
print(mat.sum(axis=0))

[55 60 65 70 75]
